# Default: use stable harmonization pipeline, site collation, pekel run, and siteSR run.
# Best for users who wish to run the pipeline to make different filtering decisions
# in the siteSR dataset.
default:
  # gmail account to associate with {googledrive}
  google_email: "therossyndicate@gmail.com"
  drive_project_folder: "~/aquamatch_siteSR_wqp/" # must start with "~/" and end with "/"
  collated_site_version: "2025-06-02" # date of stored site collation for pipeline
  run_pekel: FALSE 
  run_GEE: FALSE
  pekel_gee_version: "2025-06-02"
  update_and_share: FALSE # indication of whether of not the 'export' siteSR files should be 
  # uploaded to Drive, requires drive_project_folder if set to TRUE

# Update the stable dataset version for one or more parameters
admin_update:
  google_email: "therossyndicate@gmail.com"
  drive_project_folder: "~/aquamatch_siteSR_wqp/"
  collated_site_version: "2025-06-02"
  handoff_date: "2025-06-02"
  run_pekel: TRUE
  run_GEE: TRUE
  update_and_share: TRUE 

