# Default: Non-ROSS users: provide email and drive folder and use dynamic local versions,
# but not stable. You will need to create the specified drive folder if it does
# not already exist
default:
  # gmail account to associate with {googledrive}
  google_email: ""
  # The local directory where the harmonize {targets} pipeline is located (i.e.,
  # the pipeline that runs the download step)
  harmonize_repo_directory: "../AquaMatch_harmonize_WQP/"
  parameters: "chla,sdd" # any combination of harmonized data
  use_stable: FALSE
  drive_project_folder: "~/aquamatch_siteSR_wqp/"
# External user runs harmonization using stable datasets, creates harmonized 
# datasets in their own Google Drive
use_stable:
  google_email: "steeleb@colosate.edu"
  harmonize_repo_directory: "../AquaMatch_harmonize_WQP/"
  parameters: "chla,sdd" # any combination of harmonized data
  use_stable: TRUE
  stable_date: "20240701"
  drive_project_folder: "~/aquamatch_siteSR_wqp/"
# Update the stable dataset version for one or more parameters
admin_update:
  google_email: "therossyndicate@gmail.com"
  harmonize_repo_directory: "../AquaMatch_harmonize_WQP/"
  parameters: "chla,sdd" # any combination of harmonized data
  use_stable: TRUE
  stable_date: "20240701"
  drive_project_folder: "~/aquamatch_siteSR_wqp/"
