# yaml file to configure the Landsat C2 SR & ST parameters for this repository's 
# {targets} workflow

# The following parameters are required to be set by the user unless otherwise 
# indicated. All inputs are case-sensitive.

local_settings:
- data_dir: "~/Documents/GitHub/AquaMatch_siteSR_WQP/4_compile_sites/out/" # point to the *full* directory path where your location 
# information is stored - this path must end with a '/'
- location_file: "collated_WQP_sites.csv" # name of the *.csv* file that contains the location information
- unique_id: "siteSR_id" # this is the column that stores the unique identifier for each 
# site or polygon and should not contain any special characters
- latitude: "WGS84_Latitude" # this is the column that stores the latitude of the site, must 
# be in decimal degrees
- longitude: "WGS84_Longitude" # this is the column that stores the longitude of the site, must 
# be in decimal degrees
- location_crs: "EPSG:4326" # this is the coordinate reference system of the location data, 
# must be in EPSG format (e.g. EPSG:4326)

google_settings:
- google_email: "therossyndicate@gmail.com" # enter your google email address associated with the Earth Engine
# credentials
- proj: "siteSR" # this is a short name for file naming conventions. All output 
# files will include this prefix.
- proj_folder: "siteSR_prelim" # this is the folder name where the GEE data will be save to 
# Google Drive. If it doesn't exist, it will be created.
- ee_proj: "ee-aquamatch" # this is the ee project name you are running your pulls from
- run_date: "2025-01-13" # date of run for versioning, must be in YYYY-MM-DD foramt

temporal_settings: 
- start_date: "1983-01-01" # earliest data of satellite data to be acquired; 
# earliest data available is 1983-01-01
- end_date: "2024-12-31" # latest data of satellite data to be acquired; if 'today' 
# is used, the date will be set to the current date

spatial_settings: 
- extent: "site" # options: "site", "polygon", "polycenter", "site+polygon", 
# "site+polygon+polycenter", "polygon+polycenter" - at this time lake and lake 
# center can only be calculated for lakes in the US
- site_buffer: 200 # buffer distance in meters around the site or poly center
- site_filter: TRUE # R boolean (TRUE/FALSE) - note if sites should be filtered to only include lake/res/pond/river/stream sites or not

gee_settings:
- cloud_filter: "True" # python boolean ("True"/"False") - if True, scenes will be filtered by 
# scene-level cloudy value provided in the metadata
- cloud_thresh: 75 # scenes with a cloud value greater than this threshold will
# be filtered out
- water_detection: "DSWE" # "DSWE" is currently the only option for water 
# detection. Future iterations may include Peckel water instance or another method.
- DSWE_setting: "1a" # 1, 1a, 3, 1+3, 1a+3. 
# 1: DSWE 1 only summarizes high confidence water pixels
# 3: DSWE 3 summarizes vegetated pixels. 
# algal threshold variants (1a): 
#     DSWE 1a summarizes pixels with additive algal threshold mask. 
#     1a will also obtain DSWE1 for downstream comparison.

